### ISSUE TITLE
[Feature REQ] Info/stats on the landing page

### ISSUE THREAD

**Issue by TRaSH-** [Notifiarr/starrproxy#16]
Would be nice if we could get some more info on the landing page

![image](https://github.com/user-attachments/assets/26b62362-aa9b-4b05-95e8-526261a9cbf8)

- Show when something is blocked and you can directly link to the API app settings.
- Show updated templates.

**Comment by angrycuban13** [comment]
Agreed with this. I was trying to think what else to add to the landing page and this seems like a nice idea to start with.

**Comment by austinwbest** [comment]
sure, should be able to get some things put together
