### ISSUE TITLE
[Feature REQ] Multiple instance selection

### ISSUE THREAD

**Issue by TRaSH-** [Notifiarr/starrproxy#18]
Like many people, they run multiple instances of the same app (2x Radarr, Sonarr, etc), and the apps all use the same API access.

So now you need to add them multiple times depending on how many instances you've running which could make it look a bit messy
![image](https://github.com/user-attachments/assets/0fb7a936-cf79-4e70-bf36-9f11eb6b06a8)
![image](https://github.com/user-attachments/assets/452cc688-2b56-4c6d-a483-80172d338012)

Perhaps something like this:
![image](https://github.com/user-attachments/assets/0cb385b4-8891-44e5-ae20-f545b298b521)

**Comment by austinwbest** [comment]
This wont work, ive already tried it. For example if you add a movie in a request app and the apikey is linked to multiple radarrs, which one does it go to? Impossible to know.
